Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -26,17 +26,17 @@ jobs:
           USERNAME: ${{ secrets.USERNAME }}
           PASSWORD: ${{ secrets.PASSWORD }}
           script: |
-              # Logging start of script execution
-              echo "Starting script execution..."
+              # # Logging start of script execution
+              # echo "Starting script execution..."
             
-              # Navigate to the directory
-              if [ -d "bahja-isaac-nas-discord-chatbot" ]; then
-                cd bahja-isaac-nas-discord-chatbot || exit 1
-              else
-                echo "Error: Directory 'bahja-isaac-nas-discord-chatbot' not found."
-                exit 1
-              fi
-            
+              # # Navigate to the directory
+              # if [ -d "bahja-isaac-nas-discord-chatbot" ]; then
+              #   cd bahja-isaac-nas-discord-chatbot || exit 1
+              # else
+              #   echo "Error: Directory 'bahja-isaac-nas-discord-chatbot' not found."
+              #   exit 1
+              # fi
+              cd bahja-isaac-nas-discord-chatbot/bahja-isaac-nas-discord-chatbot
               # Pull latest changes from Git
               git pull
             
