Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -36,13 +36,13 @@ jobs:
           
 
           
-                  # # Navigate to the directory
-                  # if [ -d "bahja-isaac-nas-discord-chatbot" ]; then
-                  #   cd bahja-isaac-nas-discord-chatbot || exit 1
-                  # else
-                  #   echo "Error: Directory 'bahja-isaac-nas-discord-chatbot' not found."
-                  #   exit 1
-                  # fi
+                  # Navigate to the directory
+                  if [ -d "bahja-isaac-nas-discord-chatbot" ]; then
+                    cd bahja-isaac-nas-discord-chatbot || exit 1
+                  else
+                    echo "Error: Directory 'bahja-isaac-nas-discord-chatbot' not found."
+                    exit 1
+                  fi
       
                   # Pull latest changes from Git
                   git pull
