Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -8,30 +8,40 @@ jobs:
   execute-commands:
     name: Execute Commands
     runs-on: ubuntu-latest
-
+    
     steps:
-    
-name: Checkout Repository
-    uses: actions/checkout@v2
+      - name: Checkout Repository
+        uses: actions/checkout@v2
 
-    
-name: Execute SSH Commands
-    uses: appleboy/ssh-action@v1.0.3
-    with:
-      HOST: ${{ secrets.HOST }}
-      USERNAME: ${{ secrets.USERNAME }}
-      PASSWORD: ${{ secrets.PASSWORD }}
-      script: |
-        echo "Starting script execution..."
-        if [ -d "bahja-isaac-nas-discord-chatbot" ]; then
-          cd bahja-isaac-nas-discord-chatbot || exit 1
-        else
-          echo "Error: Directory 'bahja-isaac-nas-discord-chatbot' not found."
-          exit 1
-        fi
-        git pull
-        npm install
-        pm2 stop chatbot
-        pm2 start index.js --name chatbot
+      - name: Execute SSH Commands
+        uses: appleboy/ssh-action@v1.0.3
+        with:
+          HOST: ${{ secrets.HOST }}
+          USERNAME: ${{ secrets.USERNAME }}
+          PASSWORD: ${{ secrets.PASSWORD }}
+          script: |
+            # Logging start of script execution
+            echo "Starting script execution..."
 
-        echo "Script execution completed successfully." 
+            # Navigate to the directory
+            if [ -d "bahja-isaac-nas-discord-chatbot" ]; then
+              cd bahja-isaac-nas-discord-chatbot || exit 1
+            else
+              echo "Error: Directory 'bahja-isaac-nas-discord-chatbot' not found."
+              exit 1
+            fi
+
+            # Pull latest changes from Git
+            git pull
+
+            # Install npm dependencies
+            npm install
+
+            # Stop chatbot if running
+            pm2 stop chatbot
+
+            # Start chatbot
+            pm2 start index.js --name chatbot
+
+            # Logging completion of script execution
+            echo "Script execution completed successfully."
